### ISSUE TITLE
main differences between this fork and src

### ISSUE THREAD

**Issue by akielaries** [hellt/vrnetlab#124]
I am looking to work on options to run Juniper's vJunosEvolved and vJunos-switch products in containerlab, which is similar to how vSRX gets spun up, but am curious the core differences between hellt/vrnetlab and its source vrnetlab/vrnetlab. It appears this repo has support for vSRX while the source repo does not among other miscellaneous changes. Is hellt/vrnetlab the offical dependency for containerlab?

**Comment by hellt** [comment]
Hi @akielaries 
You probably figured it out, but for others who might stumble upon this issue, yes, `hellt/vrnetlab` is a dependency of containerlab.

**Comment by akielaries** [comment]
Yup my apologies. I had not seen the README does a great job explaining why this fork exists.
