### ISSUE TITLE
Startup config file not found

### ISSUE THREAD

**Issue by HeikkiLavaste** [hellt/vrnetlab#126]
Hi,

Is there something specific that I need to do to get the containers to have a persistent config? 
I'm have a  csr and vmx image in containerlabs and when I destroy and deploy the lab again, the config is always wiped out to basic one written by netlab. 
According to CSR boot trace, 
2023-07-07 15:50:12,785: launch     TRACE    Startup config file /config/startup-config.cfg is not found

Other images , i.e EOS, no problems. 
Docker version 24.0.3
clab version: 0.42.0

Br, 
Heikki

**Comment by hellt** [comment]
Hi,
yes, a startup-config needs to be provided, but given you're using netlab I am not sure how it is done there.
@jbemmel might know

**Comment by jbemmel** [comment]
Netlab is intent based - what's described in the config file gets applied. If Netlab is not (made) aware of pre-existing configs that should override things, it shouldn't leave those in place.

If that happens for EOS, that would be a bug...

To achieve this in general (not tested) you may be able to declare the container as 'unmanaged' and provide a clab.startup-config with the desired configuration

**Comment by HeikkiLavaste** [comment]
I'm using containerlabs and I used vrnetlab to create the containers for vmx and csr. 
I assumed the startup config would be written to a file on the docker host, like with the other "native" containerlab images. 
If not, I can save the configs some other way.

**Comment by hellt** [comment]
@HeikkiLavaste 
for VM based images it doesn't do that for these images. If you need your lab to come up in a predefined step then you have to save the intended config and provide it in clab file via `startup-config` instruction.

**Comment by hellt** [comment]
Feel free to re-open this issue if new data is available.
