### ISSUE TITLE
Low rates of throughput CSR1000V

### ISSUE THREAD

**Issue by yennym3** [hellt/vrnetlab#146]
Hi,

I'm testing the througput of the csr1000v router built with hellt/vrnetlab and I'm getting very low rates, even in certain intervals I have null values, has this been tested, would you know what could be related to such a low througput?

The topology i'm testing is two routers csr1000v connected each one to a host, the  througput test is being done with iperf3, host-1 is the iperf server and host-2 is the iperf client
<img width="485" alt="image" src="https://github.com/hellt/vrnetlab/assets/74870040/79a9e8e8-33dd-4103-8450-db6b51fb2230">

`iperf3 -c 10.0.1.2 -t 20
Connecting to host 10.0.1.2, port 5201
[  5] local 10.0.2.2 port 46488 connected to 10.0.1.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   749 KBytes  6.13 Mbits/sec    0    109 KBytes
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    0    115 KBytes
[  5]   2.00-3.00   sec   255 KBytes  2.09 Mbits/sec    0    120 KBytes
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    0    126 KBytes
[  5]   4.00-5.00   sec   255 KBytes  2.09 Mbits/sec    0    144 KBytes
[  5]   5.00-6.00   sec   318 KBytes  2.61 Mbits/sec    0    173 KBytes
[  5]   6.00-7.00   sec   445 KBytes  3.65 Mbits/sec    0    214 KBytes
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0    270 KBytes
[  5]   8.00-9.00   sec   573 KBytes  4.69 Mbits/sec    0    328 KBytes
[  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec    0    385 KBytes
[  5]  10.00-11.00  sec   827 KBytes  6.78 Mbits/sec    0    441 KBytes
[  5]  11.00-12.00  sec  0.00 Bytes  0.00 bits/sec    0    499 KBytes
[  5]  12.00-13.00  sec  1.12 MBytes  9.39 Mbits/sec    0    556 KBytes
[  5]  13.00-14.00  sec  0.00 Bytes  0.00 bits/sec    0    611 KBytes
[  5]  14.00-15.00  sec  0.00 Bytes  0.00 bits/sec    0    667 KBytes
[  5]  15.00-16.00  sec  0.00 Bytes  0.00 bits/sec    0    724 KBytes
[  5]  16.00-17.00  sec  0.00 Bytes  0.00 bits/sec    0    779 KBytes
[  5]  17.00-18.00  sec  0.00 Bytes  0.00 bits/sec    0    836 KBytes
[  5]  18.00-19.00  sec  0.00 Bytes  0.00 bits/sec    0    891 KBytes
[  5]  19.00-20.00  sec  0.00 Bytes  0.00 bits/sec   38    807 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-20.00  sec  4.46 MBytes  1.87 Mbits/sec   38             sender
[  5]   0.00-25.04  sec  2.21 MBytes   739 Kbits/sec                  receiver

`

**Comment by hellt** [comment]
you may want to configure iperf with the desired bandwidth rates, check iperf docs.
0 values might be expected since iperf meets the bw set by a client/server.

In vrnetlab/containerlab we don't have influence over the datapath performance. Can be limited by the VM pps performance, or linux networking in-between.

**Comment by yennym3** [comment]
> you may want to configure iperf with the desired bandwidth rates, check iperf docs. 0 values might be expected since iperf meets the bw set by a client/server.
> 
> In vrnetlab/containerlab we don't have influence over the datapath performance. Can be limited by the VM pps performance, or linux networking in-between.

yes, I have already tried setting the bandwidth to higher values, and modifying the TCP congestion window, but these values remain the same.

**Comment by hellt** [comment]
I don't think I can help here. Performance testing on virtual simulators is almost never a good idea since VM images are not necessarily designed for that.  
You may try to launch csr1k with qemu directly without any container wrapping that vrnetlab/containerlab impose and check the numbers again.
