### ISSUE TITLE
allow defining sros interfaces in a non consequent fashion

### ISSUE THREAD

**Issue by hellt** [hellt/vrnetlab#15]
currently its not possible to add interfaces `eth1` and `eth5` and have `eth5` correspond to port5 on the first mda. It will be treated as a second interface.

The idea is to make the interfaces respect their number in the name

**Comment by carlmontanari** [comment]
hihi #55 (tagging so we remember to close this one if that pr is solid!)

**Comment by hellt** [comment]
yay, #55 did this
