### ISSUE TITLE
Daemon to align oper state between container's `ethX` and `tapX` interfaces

### ISSUE THREAD

**Issue by hellt** [hellt/vrnetlab#150]
The issue with datapath stitching we do with tc mirred redirect between VM's `tap` interfaces and container's `eth` is that the state of the `ethX` interfaces does not propagate to the `tapX` interfaces.

This prevents users from simulating network outages when you want to shutdown a link on one end and see it go oper down on the other end.

What we can do is to package a daemon service inside the container that would watch for the oper state of `tapX<->ethX` pair and coordinate their state.

So when tapX goes down, ethX should be down and vice versa.

**Comment by mabra94** [comment]
Just want to throw ifplugd in here:
https://linux.die.net/man/8/ifplugd

Could be a potential solution to enable fate sharing between different interfaces.

**Comment by jbemmel** [comment]
Alternatively, we could add a command to containerlab that translates 'ifdown ethx' into ifdown of the correct tap interface

Then there is no need to monitor the state, as this is a relatively rare scenario

**Comment by hellt** [comment]
Unfortunately it is quite a common scenario, esp with SR OS demos where we show fast reroute and path switching. people switch off some links and expect state to be translated over the link, like it would in real life.
So overall it is a good enhancement, useful across the board.

**Comment by mabra94** [comment]
Example of how Cumulus Linux uses ifplugd:
https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-56/Layer-1-and-Switch-Ports/Interface-Configuration-and-Management/ifplugd/

Will look into that in more detail as soon as I find time..

**Comment by mabra94** [comment]
Looks like the state of the TAP interface is not even propagated into the VM. Did some quick checks manually disabling interfaces (eth and tap) in a vrnetlab based container which had no effect at all inside the VM.

**Comment by hellt** [comment]
yeah, this is a pity
I don't think it is fair to create automation that brings admin state to down once tap is down, so my thinking is to let this be handled by a uses.
