### ISSUE TITLE
ipinfusion OcNOS 6.4.1 not working

### ISSUE THREAD

**Issue by johncrack** [hellt/vrnetlab#158]
Hi,

I'm getting the following error when I try to make a docker image from ipinfusion OcNOS image.

I'm not sure to understand what's wrong.

`[root@containerlab ocnos]# make docker-image
for IMAGE in OcNOS-SP-MPLS-x86-6.4.1-37-GA.qcow2; do \
	echo "Making $IMAGE"; \
	make IMAGE=$IMAGE docker-build; \
done
Making OcNOS-SP-MPLS-x86-6.4.1-37-GA.qcow2
make[1]: Entering directory '/root/vrnetlab/ocnos'
rm -f docker/*.qcow2* docker/*.tgz* docker/*.vmdk* docker/*.iso
Building docker image using OcNOS-SP-MPLS-x86-6.4.1-37-GA.qcow2 as vrnetlab/vr-ocnos:
cp ../common/* docker/
make IMAGE=$IMAGE docker-build-image-copy
make[2]: Entering directory '/root/vrnetlab/ocnos'
cp OcNOS-SP-MPLS-x86-6.4.1-37-GA.qcow2* docker/
make[2]: Leaving directory '/root/vrnetlab/ocnos'
(cd docker; docker build --build-arg http_proxy= --build-arg https_proxy= --build-arg IMAGE=OcNOS-SP-MPLS-x86-6.4.1-37-GA.qcow2 -t vrnetlab/vr-ocnos: .)
[+] Building 0.0s (0/0)                                                                                                                                                                      docker:default
ERROR: invalid tag "vrnetlab/vr-ocnos:": invalid reference format
make[1]: *** [../makefile.include:29: docker-build-common] Error 1
make[1]: Leaving directory '/root/vrnetlab/ocnos'
make: *** [../makefile.include:9: docker-image] Error 2
[root@containerlab ocnos]#`

**Comment by hellt** [comment]
Hi @johncrack 
this is because the version pattern has changed it seems.
You can rename your image to follow the pattern used - https://github.com/hellt/vrnetlab/blob/master/ocnos/Makefile#L8

Then it should start the build process.
Feel free to reopen this if the renaming wouldn't work
