### ISSUE TITLE
vJunos Switch not showing interfaces

### ISSUE THREAD

**Issue by c235tgfer** [hellt/vrnetlab#163]
Hello - I've deployed the latest build of vrnetlab and used it to build a vJunos Switch for use in containerlab however I can't see any of the ge-* interfaces within Junos itself.

Looking at the deployment steps here https://www.juniper.net/documentation/us/en/software/vjunos/vjunos-switch-kvm/topics/deploy-and-manage-vjunos-switch-onkvm.html it shows an XML file being used to tell the vSwitch how many interfaces to build and what bridges to connect them to. 

I've been through all the files in the vjunosswitch folder and can't see this XML being referenced anywhere.. are we missing a step from the build process in vrnetlab ?
Or have I missed a config/setup step somewhere?

Any help much appreciated!

**Comment by hellt** [comment]
without pasting the topology you tried and logs from the container it is impossible to say anythign
