### ISSUE TITLE
How to build Cisco 8000 container images?

### ISSUE THREAD

**Issue by berkutcloud** [hellt/vrnetlab#169]
I can see from [this Cisco 8000 kinds page](https://containerlab.dev/manual/kinds/c8000/) that the Cisco 8000 is a supported kind in containerlab. However I don't see a directory for c8000 in vrnetlab and I was wondering how to build the images for this platform. I have a tgz file `c8000v-17.11.01a.tgz` that only has a `virtioa.qcow2` file inside, so I cannot follow the directions on the kind page for Cisco 8000. The download page for CIsco 8000 doesn't mention anything about containerlab images as hinted to on the kind page for Cisco 8000. Any help would be appreciated.

**Comment by hellt** [comment]
The support for c8000v was added by a source from/close to cisco, indeed there is no vrnetlab code for that, and no one shared how to start it.

Seems like this image is controlled by the vendor.
