### ISSUE TITLE
Support for IOSv & IOSvL2

### ISSUE THREAD

**Issue by aj-cruz** [hellt/vrnetlab#173]
Has there been any discussions about adding support for IOSv & IOSvL2?

**Comment by hellt** [comment]
Aren't those images long EOL'ed? It has been asked a long while ago, but seems like there is little interest in those platforms

**Comment by aj-cruz** [comment]
@hellt The IOSvL2 image was last updated in 2020, but they're actively used in the latest versions of Cisco Modeling Labs (CML). I know I'm interested in labbing Cisco Catalyst switching and lightweight routers (much lighter than CSR & 8Kv).
In case you're keeping track, you have my vote for them. Thanks.

**Comment by hellt** [comment]
Got it. We are welcoming contributions, so if anyone is willing to help the community -- we will support this
