### ISSUE TITLE
Incorrect memory and cpu count for cisco/n9kv image

### ISSUE THREAD

**Issue by rohit04saluja** [hellt/vrnetlab#260]
The current CPU count and memory with which n9kv boots is 8GB and 1 CPU. This differs from [Cisco documentation](https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/105x/configuration/n9000v-9300v-9500v/cisco-nexus-9000v-9300v-9500v-guide-release-105x/m-overview.html) which states that the minimum should be 10GB and 4CPU.

This is resulting in slower boot time.

**Comment by rohit04saluja** [comment]
Open #261 for the same.

**Comment by hellt** [comment]
closed by #261
