### ISSUE TITLE
CSR1000v make fails due to f-string in vrnetlab.py

### ISSUE THREAD

**Issue by dpnetca** [hellt/vrnetlab#43]
CSR1000v docker file is set to use Debian:stretch which installs python 3.5.3 which does not support f-strings. (fstring support was added in python 3.6 I beleive). As f-strings are used in vrnetlab.py this causes the build to fail with a syntax error:

```
Step 10/10 : ENTRYPOINT ["/launch.py"]
 ---> Using cache
 ---> 6388d8f13b7b
Successfully built 6388d8f13b7b
Successfully tagged vrnetlab/vr-csr:16.11.01b
docker run --cidfile cidfile --privileged vrnetlab/vr-csr:16.11.01b --trace --install
Traceback (most recent call last):
  File "/launch.py", line 13, in <module>
    import vrnetlab
  File "/vrnetlab.py", line 51
    logging.getLogger().info(f"Delaying VM boot of by {delay} seconds")
                                                                     ^
SyntaxError: invalid syntax
make[1]: *** [Makefile:19: docker-build] Error 1
make[1]: Leaving directory '/home/denis/vrnetlab/csr'
```

Changing docker to use to debian:buster resolves that issue, but then get errors on conn_mode not existing on the CSR class...

**Comment by dpnetca** [comment]
Digging into this some more, this appears to be due to changes you made in your forked repo to the vrnetlab.py

Looking at changes you have made to launch.py on XRV9K from original repo,  looks like this should be fairly simple to replicate similar changes to the CSR as well...I think have this completed, will test and submit PR with changes if test work

**Comment by hellt** [comment]
Hi @dpnetca 
you are completely right, the CSR1000v was not (yet) reworked in this fork, since it was not yet added to [containerlab](https://containerlab.srlinux.dev).

It should be quite straightforward to add it, though, a typical set of changes is captured in this PR - https://github.com/hellt/vrnetlab/pull/42

**Comment by dpnetca** [comment]
That is what I am working towards is getting it into containerlab.  I have it partially working, docker image builds, I can load it into containerlab, but I am not getting all interfaces showing up (loading manually or via containerlab). So that's what I need to work through next.  As it stand now, Gi2 and Gi3 load and I can connect and ping between. But I do not yet get Gi1, or a  4th interface or higher interface to load.

**Comment by hellt** [comment]
cool. Let me know if you get stuck, I can have a look at it as well

**Comment by dpnetca** [comment]
so, I have it working with CSR1000v IOS version `Cisco IOS XE Software, Version 17.03.02`  

with version 16.12.05 and 16.11.01b for some reason gig1 doesn't get created...  

I want  to do a bit more testing with 17.03.02 but if it works as it seems to be I can submit a PR for this w/ this version working atleast gets part way there

**Comment by hellt** [comment]
thanks @dpnetca 
sure, if the newer version works that warrants a PR, later we can check what is wrong with the older one if there is a need

**Comment by hellt** [comment]
One other comment from good ntc folks which might help in trying things

```
cfg_file.write("do clear platform software vnic-if nvtable\r\n\r\n")
```

this is expanded here and by quickly glancing over it https://www.cisco.com/c/en/us/td/docs/routers/csr1000/software/configuration/b_CSR1000v_Configuration_Guide/b_CSR1000v_Configuration_Guide_chapter_01010.html it might help.
The assumption is that during the install there is this mythical nic<->mac table gets populated, which needs to be cleared before commiting the image.

Worth trying imo
