### ISSUE TITLE
add support for broadcom-sonic/sonic-vs

### ISSUE THREAD

**Issue by fire-ant** [hellt/vrnetlab#65]
I think we should add support for full-fat sonic vm (the non p4 variant) to containerlab and by proxy vrnetlab.

Broadcom have cut a vm here https://github.com/Broadcom/sonic-VirtualSwitch and for some reason the sonic upstream Jenkins pipeline now asks me for GitHub auth to continue to consume it (I might raise this in parallel.

Im unsure which is better to support but it would be nice to use at least one variant in conjunction with both lab projects.

**Comment by hellt** [comment]
we got a contribution for the upstream sonic vm in #220

**Comment by hellt** [comment]
looks like bcom removed their image altogether
https://github.com/Broadcom/sonic-VirtualSwitch/commit/04b4e182c6fd1cf55e49c649bc64208bd2f18964
