### ISSUE TITLE
vMX make fails under Ubuntu 21.10

### ISSUE THREAD

**Issue by jan-linx** [hellt/vrnetlab#74]
When trying to build the vMX docker image, the script always fails at step 4.
`The command '/bin/sh -c apt-get update -qy  && apt-get upgrade -qy  && apt-get install -y     bridge-utils     iproute2     python3-ipy     socat     qemu-kvm     tcpdump     procps     openvswitch-switch  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100`

The commands mentioned in step 4 can all be executed successfully separately (after prepending sudo) and the mentioned domain names are all resolvable and reachable.

I am using a clean install of Ubuntu 21.10 (it apparently works on Rocky Linux 8.0):
Linux clab1-lab 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[make-output.txt](https://github.com/hellt/vrnetlab/files/8102572/make-output.txt)

**Comment by hellt** [comment]
The error indicates that DNS fails to resolve Ubuntu packages servers from
within the container.
You can run Ubuntu container on your host manually and do 'apt update' to
check if that work

**Comment by jan-linx** [comment]
Yes, that is the case, but I wonder why... On the docker host, the same resolver is configured and it works.

_$ sudo docker run -it ubuntu
root@1248924c005e:/# cat /etc/resolv.conf
nameserver 8.8.8.8
search linx.net
root@1248924c005e:/# apt update
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
0% [Connecting to archive.ubuntu.com]^C_

**Comment by hellt** [comment]
there are several potential reasons
you will have to use tcpdump and check iptables rules to see what is
blocking the outgoing DNS requests

**Comment by jan-linx** [comment]
The ubuntu container is a barebone install so not even tools like ping or ip-tools are available. 

Which image does vrnetlab use to containerise the VM? ubuntu:20.04?
linx@clab1-lab:~/labs/vr01$ sudo docker images
REPOSITORY              TAG        IMAGE ID       CREATED        SIZE
<none>                  <none>     b34878576bd6   27 hours ago   72.8MB << this seems to be the failed containerisation of the vMX?
vrnetlab/vr-sros        20.10.R6   e6ca518e1e9a   2 days ago     997MB
ubuntu                  20.04      54c9d81cbb44   2 weeks ago    72.8MB << and this is used by vrnetlab to containerise the VMs?
ubuntu                  latest     54c9d81cbb44   2 weeks ago    72.8MB

**Comment by hellt** [comment]
yes, vrnetlab uses ubuntu:20.04 as a base image
you can use `hellt/network-multitool` as a testing image, it has most networking utilities installed

**Comment by jan-linx** [comment]
Yes, iptables was dropping traffic initiated by the container, allowing bidirectional traffic fixed that issue:
_Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
 3555  299K ACCEPT     all  --  labctrl docker0  0.0.0.0/0            0.0.0.0/0
 9050  760K ACCEPT     all  --  docker0 labctrl  0.0.0.0/0            0.0.0.0/0
30267 4492K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0_

This wasn't necessary when building the SR-OS containers, do you use another base image which already contains everything required, or is it the same Ubuntu 20.04 base image but SR-OS doesn't require additional packages to be installed?

**Comment by hellt** [comment]
no, SR OS uses the same image and installs some packages as well
and normally you don't need to install those iptables rules for traffic from a container to external networks. Those rules are typically needed when you need to allow a traffic from external systems towards containers.

So likely you had some iptables misconfiguration that caused DNS to fail

**Comment by jan-linx** [comment]
This was a fresh Ubuntu 21.10 install. The only thing I have installed afterwards was docker, containerlab and vrnetlab. The iptables prior to me adding the two lines to the DOCKER-USER chain looked like this:

```
$ sudo iptables -nvL
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
15747 2530K DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
15747 2530K DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      labctrl  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
15747 2530K DOCKER     all  --  *      labctrl  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  labctrl !labctrl  0.0.0.0/0            0.0.0.0/0
15747 2530K ACCEPT     all  --  labctrl labctrl  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  labctrl !labctrl  0.0.0.0/0            0.0.0.0/0
    3   252 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
15747 2530K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      labctrl  0.0.0.0/0            0.0.0.0/0
 5494  461K DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
46014 7022K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

$ sudo iptables-legacy -nvL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

```

**Comment by hellt** [comment]
yes, with these default rules normally you should have external access from container to DNS/Internet
in any case, this issue is not related to vmx and has to do with your container host
